### PR TITLE
Solution: moved %Quantum.Jobs{nodes: ...} defaulting to the normalizer, to execute defaulting logic at the time the job is actually added to the scheduler.

### LINKED ISSUE #89: Quantum.add_job("name", job) API does not work
Dudes, hu there again!

Weird, but Quantum.add_job("name", job) where job is %Quantum.Job{} does not work.

First off, everithing works fine when I add a job like this:
Quantum.add_job("* * * * *", fn -> IO.puts "Tick" end)

so I have :quantum app up and running and nothins is wrong with it.

Now, when I use the add_job API passing it the %Quantum.Job{} struct as you have carefully described in the readme.md, same stuff does not work.

Any clues?

I mean it looks really weird as this seems to be the very basic stuff that should just work if the quantum app is up and running.

I'm using [**{:quantum, ">= 1.7.0"}]** dependency.

Any pointers are highly appreciated. I'm also using the timezone: :local option if that is important.

Thanks, Dmitry.

### LINKED ISSUE #93: Nodes property is not correctly defaulted in %Quantum.Job{} struct
nodes property in `%Quantum.Job{}` struct is defaulted to `:nonode@nohost` when the application is run in a named node.

Repro steps:

1. Create a new project
2. Add a dependency as follows: `{:quantum, ">= 1.7.0"}`
3. Get and compile dependencies and start a ies on a named node via --sname option
4. define a job like this: `job = %Quantum.Jobs{name: "I am a job", schedule: "* * * * *", task: {IO, :puts}, args: ["You will never see me..."]}`
5. Add a job to the Quantum via `Quantum.add_job(job.name, job)`
6. Verify nothing is printed after a minute boundary is crossed (and never printed if you are patient enough)
7. create asnother job in this session as follows: `noded_job = %{job | args: ["I will print every other minute"], nodes: [node()]}`
8. Add a noded_job to Quantum: Quantum.add_job("noded job", noded_job)
9. Validate every other minute the job prints "I will print every other minute" to the console.

### PR DESCRIPTION
**Pull request by dapdizzy**
Moved defaulting logic for nodes property of the %Quantum.Job struict to the normalizer to make a runtime call at the time the job is actually added to the scheduler, instead of using a wrong static value.

Added public functon default_nodes to the Quantum.Normalizer module in order to explicitly set nodes property in the %Quantum.Job{} struct in tests that explicitly validate nodes property.

Fixes #89 Fixes #93

### CODE REVIEW

File: lib/quantum/normalizer.ex [hunk 1]
```diff
@@ -28,6 +32,12 @@ defmodule Quantum.Normalizer do
   defp normalize_job({job_name, %Quantum.Job{} = job}) do
     # Sets defauts for job if necessary
     job_name |> job_opts([]) |> Map.merge(%{job | name: job_name})
+    |> Map.put(
+        :nodes,
+        case job.nodes do
+          nil -> default_nodes
```
Comment (dapdizzy) [inline lib/quantum/normalizer.ex]: This way we set the default value only when there is no value provided, i.e., th evalue is nil, whilst Map.merge overrides the value, thus it is not a suitable mechanism for defaulting, honoring user defined value, if any.

File: lib/quantum/normalizer.ex [hunk 2]
```diff
@@ -28,6 +32,12 @@ defmodule Quantum.Normalizer do
   defp normalize_job({job_name, %Quantum.Job{} = job}) do
     # Sets defauts for job if necessary
     job_name |> job_opts([]) |> Map.merge(%{job | name: job_name})
```
Comment (dapdizzy) [inline lib/quantum/normalizer.ex]: Just want to mention, that this overrides the name property regardless of the value that was or was not specified by the user, which means it is not 'defaulting', but rather 'overriding'.

File: test/quantum_test.exs [hunk 3]
```diff
@@ -79,7 +90,7 @@ defmodule QuantumTest do
     for name <- job_names do
       spec = "* * * * *"
       fun = fn -> :ok end
-      job = %Quantum.Job{name: name, schedule: spec, task: fun}
+      job = %Quantum.Job{name: name, schedule: spec, task: fun, nodes: Quantum.Normalizer.default_nodes}
```
Comment (dapdizzy) [inline test/quantum_test.exs]: Now we have to explicitly pass the nodes default value for tests that validate job as a struct.
